# Dependencies
markdown:         redcarpet
pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            Gautham Shankar
tagline:          'Random thoughts'
description:      'A brazen two-column <a href="http://jekyllrb.com" target="_blank">Jekyll</a> theme that pairs a prominent sidebar with uncomplicated content. Made by <a href="https://twitter.com/mdo" target="_blank">@mdo</a>.'
url:              http://gauthamshankar.com
baseurl:          /

author:
  name:           'Gautham Shankar'
  url:            https://twitter.com/gtamshankar

paginate:         5

# Custom vars
version:          2.1.0
